org.osgi.framework.storage.clean=onFirstInit
felix.auto.deploy.action=install,start
felix.auto.deploy.dir=bundle
felix.log.level=4
org.osgi.framework.system.packages.extra=javafx.application,javafx.stage,javafx.scene,javafx.scene.control,javafx.scene.layout,javafx.fxml,javafx.event,javafx.util,javafx.beans,javafx.beans.property,javafx.beans.value,javafx.collections,javafx.scene.chart,javafx.scene.shape,javafx.scene.paint,javafx.scene.text,javafx.geometry,javafx.animation
